-- Megamenu — artikel/link list + editorial (marketing) card per kategori.
-- Sebelum ini kontennya hardcode di messages/*.json (megamenu.<key>.links /
-- .editorialTitle) + gambar statis di megamenu-data.ts. Tabel ini membuat
-- keduanya bisa diedit dari dashboard, sama seperti product_categories.
--
-- Jalankan di Supabase dashboard -> SQL Editor -> New query -> Run.
-- Jalankan SETELAH product-section.sql dan
-- product-wealth-management-merge.sql (category_key mengacu ke
-- product_categories, yang harus sudah punya baris Wealth Management/
-- Transaksi).
-- Aman dijalankan ulang (idempotent).

-- ---------------------------------------------------------------- tabel ----

create table if not exists public.megamenu_links (
  id           bigint generated by default as identity primary key,
  category_key text not null
               references public.product_categories(key) on delete cascade,
  label        text    not null,
  -- 'video' menampilkan ikon play di panel; null/'article' tidak.
  type         text    check (type in ('article', 'video')),
  sort_order   int     not null default 0,
  is_active    boolean not null default true,
  label_en     text,
  label_zh     text
);

create index if not exists megamenu_links_category_sort_idx
  on public.megamenu_links (category_key, sort_order);

create table if not exists public.megamenu_editorial (
  category_key text primary key
               references public.product_categories(key) on delete cascade,
  title        text not null,
  -- Path relatif (/assets/category/x.webp) atau URL Supabase Storage.
  image        text not null,
  title_en     text,
  title_zh     text
);

-- ------------------------------------------------------------------ RLS ----

alter table public.megamenu_links     enable row level security;
alter table public.megamenu_editorial enable row level security;

drop policy if exists "public read active megamenu links" on public.megamenu_links;
create policy "public read active megamenu links"
  on public.megamenu_links for select to anon, authenticated
  using (is_active);

drop policy if exists "public read megamenu editorial" on public.megamenu_editorial;
create policy "public read megamenu editorial"
  on public.megamenu_editorial for select to anon, authenticated
  using (true);

-- ----------------------------------------------------------------- seed ----
-- Isi sama persis dengan messages/id.json ("megamenu") + gambar dari
-- megamenu-data.ts saat ini, supaya tampilan tidak berubah begitu section
-- baca dari sini. Investasi + Asuransi digabung ke "Wealth Management".

delete from public.megamenu_links where category_key in
  ('Simpanan', 'Kartu Kredit', 'Pinjaman', 'e-Banking', 'Wealth Management', 'Transaksi');

insert into public.megamenu_links (category_key, label, type, sort_order, label_en, label_zh) values
  ('Simpanan', 'Cara top up & transfer antar rekening', 'video', 1,
    'How to top up & transfer between accounts', '如何在账户之间充值和转账'),
  ('Simpanan', 'Perbedaan Tahapan, Tapres, dan Deposito', null, 2,
    'Differences between Tahapan, Tapres, and Deposito', 'Tahapan、Tapres 和定期存款的区别'),
  ('Simpanan', 'Berapa saldo minimum dan biaya admin tiap produk simpanan?', null, 3,
    'What is the minimum balance and admin fee for each savings product?', '每种储蓄产品的最低余额和管理费是多少？'),
  ('Simpanan', 'Syarat & dokumen pembukaan rekening BCA', null, 4,
    'Requirements & documents to open a BCA account', '开设BCA账户所需的条件和文件'),

  ('Kartu Kredit', 'Cara ajukan kartu kredit via website', 'video', 1,
    'How to apply for a credit card via website', '如何通过网站申请信用卡'),
  ('Kartu Kredit', 'Kartu kredit mana yang cocok untuk saya?', null, 2,
    'Which credit card suits me best?', '哪种信用卡适合我？'),
  ('Kartu Kredit', 'Syarat pengajuan kartu kredit BCA', null, 3,
    'Requirements for a BCA credit card application', 'BCA信用卡申请条件'),
  ('Kartu Kredit', 'Cara bayar tagihan kartu kredit BCA', null, 4,
    'How to pay a BCA credit card bill', '如何支付BCA信用卡账单'),

  ('Pinjaman', 'Proses pengajuan dari awal hingga cair', 'video', 1,
    'The application process from start to disbursement', '从申请到放款的完整流程'),
  ('Pinjaman', 'Cara mengajukan KPR online lewat myBCA', null, 2,
    'How to apply for a home loan online via myBCA', '如何通过myBCA在线申请房贷'),
  ('Pinjaman', 'Syarat & dokumen pengajuan pinjaman di BCA', null, 3,
    'Requirements & documents for a BCA loan application', 'BCA贷款申请所需条件和文件'),
  ('Pinjaman', 'Berapa maksimal pinjaman yang bisa saya ajukan?', null, 4,
    'What is the maximum loan amount I can apply for?', '我最多可以申请多少贷款？'),

  ('e-Banking', 'Cara aktivasi myBCA untuk pengguna baru', 'video', 1,
    'How new users activate myBCA', '新用户如何激活myBCA'),
  ('e-Banking', 'Cara top up Flazz lewat myBCA', null, 2,
    'How to top up Flazz via myBCA', '如何通过myBCA为Flazz充值'),
  ('e-Banking', 'Fitur-fitur unggulan myBCA', null, 3,
    'myBCA''s key features', 'myBCA的主要功能'),
  ('e-Banking', 'Apa perbedaan myBCA dan KlikBCA?', null, 4,
    'What is the difference between myBCA and KlikBCA?', 'myBCA和KlikBCA有什么区别？'),

  -- Wealth Management: gabungan link Investasi + Asuransi (masing-masing diambil 2 teratas).
  ('Wealth Management', 'Panduan memilih produk investasi sesuai profil risiko', 'video', 1,
    'A guide to choosing investments that fit your risk profile', '根据风险偏好选择投资产品的指南'),
  ('Wealth Management', 'Cara beli Reksa Dana lewat myBCA', null, 2,
    'How to buy mutual funds via myBCA', '如何通过myBCA购买共同基金'),
  ('Wealth Management', 'Memilih asuransi yang tepat untuk keluargamu', null, 3,
    'Choosing the right insurance for your family', '为您的家人选择合适的保险'),
  ('Wealth Management', 'Apa perbedaan asuransi jiwa dan asuransi kesehatan?', null, 4,
    'What is the difference between life and health insurance?', '人寿保险和健康保险有什么区别？'),

  ('Transaksi', 'Cara Praktis Top-Up Flazz Langsung dari myBCA', 'video', 1,
    'An easy way to top up Flazz directly from myBCA', '直接通过myBCA为Flazz充值的简便方法'),
  ('Transaksi', 'Panduan Lengkap Kirim Uang ke Luar Negeri', null, 2,
    'A complete guide to sending money abroad', '海外汇款完整指南'),
  ('Transaksi', 'Syarat dan Cara Mencairkan Dana Firecash di Kantor Cabang Terdekat Tanpa Potongan', null, 3,
    'How to withdraw Firecash funds at the nearest branch with no deduction', '如何在最近的分行免手续费提取Firecash资金')
on conflict do nothing;

delete from public.megamenu_editorial where category_key in
  ('Simpanan', 'Kartu Kredit', 'Pinjaman', 'e-Banking', 'Wealth Management', 'Transaksi');

insert into public.megamenu_editorial (category_key, title, image, title_en, title_zh) values
  ('Simpanan', 'Buka Rekening, Dapatkan Cashback QRIS Hingga Rp100.000',
    '/assets/category/simpanan.webp',
    'Open an account, get up to Rp100,000 QRIS cashback',
    '开户即可获得高达10万印尼盾的QRIS返现'),
  ('Kartu Kredit', 'Apply Kartu Kredit Sekarang, Gratis Iuran Tahunan Seumur Hidup & Welcome Bonus Rp500.000',
    '/assets/category/kartu-kredit.webp',
    'Apply for a credit card now — lifetime free annual fee & a Rp500,000 welcome bonus',
    '立即申请信用卡，终身免年费，另享50万印尼盾开卡礼'),
  ('Pinjaman', 'Bunga KPR Spesial 2,99% di Tahun Pertama',
    '/assets/category/pinjaman.webp',
    'Special 2.99% home loan rate in the first year',
    '首年特惠房贷利率2.99%'),
  ('e-Banking', 'Belanja Pakai QRIS di myBCA Banking, Dapatkan Diskon Hingga 50% di Merchant Pilihan',
    '/assets/category/simpanan.webp',
    'Pay with QRIS in myBCA and get up to 50% off at selected merchants',
    '在myBCA中使用QRIS支付，指定商户享最高50%折扣'),
  ('Wealth Management', 'Investasi dan Proteksi dalam Satu Genggaman, Mulai dari Rp10 Ribu',
    '/assets/category/investasi.webp',
    'Investment and protection in one app, starting from Rp10,000',
    '投资与保障一站式服务，最低1万印尼盾起'),
  ('Transaksi', 'Kirim Uang ke Luar Negeri Bebas Biaya Telex & Dapatkan Nilai Tukar Kurs Paling Spesial',
    '/assets/category/simpanan.webp',
    'Send money abroad with no telex fee and a special exchange rate',
    '海外汇款免电报费，享特惠汇率')
on conflict (category_key) do update
  set title    = excluded.title,
      image    = excluded.image,
      title_en = excluded.title_en,
      title_zh = excluded.title_zh;
